language: android
jdk: oraclejdk8
before_install:
  - chmod +x gradlew
  - yes | sdkmanager "platforms;android-30"

env:
  global:
    - ANDROID_API_LEVEL=30
    - ANDROID_BUILD_TOOLS_VERSION=30.0.2
    - TRAVIS_SECURE_ENV_VARS=true

android:
  components:
    # The BuildTools version used by your project
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - extra-android-m2repository
    - extra-google-android-support

    # The SDK version used to compile your project
    - android-$ANDROID_API_LEVEL
  licenses:
    - '.+'

script:
  - ./gradlew clean
  #    - ./gradlew install
  #    - ./gradlew bintrayUpload
  - ./gradlew assembleDebug